### ISSUE TITLE
README - initial setup improvements

### ISSUE THREAD

**Issue by sebasmonia** [davidshepherd7/fill-function-arguments#5]
For C-derived modes (like C# mode) you need to override the mode's binding `c-fill-paragraph`.
A sample:

```
(use-package csharp-mode ;; manual load since I removed omnisharp
  :demand
  :hook
  (csharp-mode-hook . (lambda () (setq-local fill-function-arguments-first-argument-same-line t)
                                 (setq-local fill-function-arguments-second-argument-same-line t)
                                 (setq-local fill-function-arguments-last-argument-same-line t)
                                 (define-key csharp-mode-map [remap c-fill-paragraph] 'fill-function-arguments-dwim))))
```

Also, for Elisp the docs are missing the last line that binds `fill-function-arguments-dwim` :)

**Comment by davidshepherd7** [comment]
> Also, for Elisp the docs are missing the last line that binds fill-function-arguments-dwim :)

I think that should be handled by the prog mode binding, is it not?

> For C-derived modes (like C# mode) you need to override the mode's binding c-fill-paragraph.

Thanks, I'll add a note about it to the readme.

**Comment by sebasmonia** [comment]
It didn't work for me but I might have done something else wrong.
Maybe prog-mode-hook runs first and then the elisp mode over-overrrides the binding?

**Comment by davidshepherd7** [comment]
>  Maybe prog-mode-hook runs first and then the elisp mode over-overrrides the binding?

Yeah that might be it, or if you're using an older version of Emacs: I think a few modes didn't derive from prog mode correctly for a while.

**Comment by sebasmonia** [comment]
I using the pre-release of 27.

Thank you for the amazing package! I love it already. Great to keep those lines under 80 chars when needed :)
