### ISSUE TITLE
fill-function-arguments-indent-after-fill is in the wrong group - also, allow using a custom function

### ISSUE THREAD

**Issue by sebasmonia** [davidshepherd7/fill-function-arguments#6]
I was trying to figure out why my C# code wasn't indented properly after using this (super handy!) package.

So I found out about the option `fill-function-arguments-indent-after-fill`, which is not part of the main defcustom group.
In addition, it would be nice to make it so that the option is a function that defaults to `indent-region` but can be overridden for certain modes. then for example in C-mode or csharp-mode you could do:
```
  (add-hook 'csharp-mode-hook (lambda ()
                              (setq-local fill-function-arguments-first-argument-same-line t)
                              (setq-local fill-function-arguments-indent-after-fill #'c-indent-line-or-region)
                              (local-set-key (kbd "M-q") #'fill-function-arguments-dwim)))
```

**Comment by davidshepherd7** [comment]
Oops, thanks for pointing out the incorrect group!

> So I found out about the option fill-function-arguments-indent-after-fill, which is not part of the main defcustom group.
In addition, it would be nice to make it so that the option is a function that defaults to indent-region but can be overridden for certain modes. then for example in C-mode or csharp-mode you could do: ...

Huh, I thought that `indent-region` was always supposed to be the canonical way to indent in any mode (because it just calls `indent-according-to-mode` etc). Do you know why it doesn't do what you want?

I added the option anyway because it was easy and it seems useful. Let me know if it works for you :slightly_smiling_face:

**Comment by sebasmonia** [comment]
Thank you so much! I will test more thoroughly in January when I have access to better C# code samples. A quick run with smallish code was positive.

I have no idea why a different function was called! I know csharp-mode inherits from cc-mode which is pretty old and sometimes doesn't follow "modern emacs conventions".

**Comment by sebasmonia** [comment]
Very late update, turns out that the one breaking the indentation was lsp-mode :) it sets `indent-region-function` to use a call to the language server. That explains is why after my test at home, my work setup was broken (no LSP at home). However, the function feature was still useful, from my `use-package` setup:

```
(csharp-mode-hook . (lambda ()
                        (setq-local fill-function-arguments-first-argument-same-line t)
                        (setq-local fill-function-arguments-second-argument-same-line nil)
                        (setq-local fill-function-arguments-last-argument-same-line t)
                        (setq-local fill-function-arguments-indent-after-fill
                                    (lambda (start end)
                                      (let ((indent-region-function #'c-indent-region))
                                        (indent-region start end))))))
```
